# NIPALS: Non-linear Iterative PArtial Least Squares

In [10]:
import numpy as np
import random

In [11]:
x = np.array([[4,9,6,7,7,8,3,2],
              [6,15,10,15,17,22,9,4],
              [8,21,14,23,27,36,15,6],
              [10,21,14,13,11,10,3,4],
              [12,27,18,21,21,24,9,6],
              [14,33,22,29,31,38,15,8],
              [16,33,22,19,15,12,3,6],
              [18,39,26,27,25,26,9,8],
              [20,45,30,35,35,40,15,10]])
y = np.array([[1, 1],[3, 1],[5, 1],[1, 3],[3, 3],[5, 3],[1 ,5],[3, 5],[5 ,5]])
X=x[:-1,:]
Y=y[:-1,:]

<img src='./images/nipals.png'>

$$\mathbf{X}_{a}=normalize(\mathbf{X})$$
$$\mathbf{Y}_{a}=normalize(\mathbf{Y})$$

* Arrow 1: Perform 𝐾 regressions, regressing each column from $\mathbf{X}_{a}$ onto the vector $\mathbf{u}_{a}$. The slope coefficients from the regressions are stored as the entries in $\mathbf{w}_{a}$. Columns in $\mathbf{X}_{a}$ which are strongly correlated with $\mathbf{u}_{a}$ will have large weights in $\mathbf{w}_{a}$, while unrelated columns will have small, close to zero, weights. We can perform these regression in one go:
$$\mathbf{w}_{a}=(\mathbf{u}_{a}^{'}\mathbf{u}_{a})^{-1}\mathbf{X}_{a}^{'}\mathbf{u}_{a}$$
* Normalize the weight vector to unit length:
$$\mathbf{w}_{a}=\frac{\mathbf{w}_{a}}{\sqrt{\mathbf{w}_{a}^{'}\mathbf{w}_{a}}}$$
* Regress every row in $\mathbf{x}_{a}$ onto the weight vector. The slope coefficients are stored as entries in $\mathbf{t}_{a}$. This means that rows in $\mathbf{x}_{a}$ that have a similar pattern to that described by the weight vector will have large values in $\mathbf{t}_{a}$. Observations that are totally different to $\mathbf{w}_{a}$ will have near-zero score values. These $N$ regressions can be performed in one go:
$$\mathbf{t}_{a}=(\mathbf{w}_{a}^{'}\mathbf{w}_{a})^{-1}\mathbf{X}_{a}^{'}\mathbf{w}_{a}$$
* Arrow 4 Next, regress every column in $\mathbf{y}_{a}$ onto this score vector, $\mathbf{t}_{a}$. The slope coefficients are stored in $\mathbf{q}_{a}$. We can calculate all $M$ slope coefficients:
$$\mathbf{q}_{a}=(\mathbf{t}_{a}^{'}\mathbf{t}_{a})^{-1}\mathbf{Y}_{a}^{'}\mathbf{t}_{a}$$
Arrow 5 Finally, regress each of the $N$ rows in $\mathbf{y}_{a}$ onto this weight vector, $\mathbf{q}_{a}$. Observations in $\mathbf{y}_{a}$ that are strongly related to $\mathbf{q}_{a}$ will have large positive or negative slope coefficients in vector $\mathbf{u}_{a}$:
$$\mathbf{u}_{a}=(\mathbf{q}_{a}^{'}\mathbf{q}_{a})^{-1}\mathbf{Y}_{a}\mathbf{q}_{a}$$
This is one round of the NIPALS algorithm. We iterate through these 4 arrow steps until the $\mathbf{u}_{a}$ vector does not change much. On convergence, we store these 4 vectors: $\mathbf{w}_{a}$, $\mathbf{t}_{a}$, $\mathbf{q}_{a}$ and $\mathbf{u}_{a}$ which jointly define the $a^{th}$ component.
Then we deflate. Deflation removes variability already explained from $\mathbf{X}_{a}$ and $\mathbf{Y}_{a}$. Deflation proceeds as follows:

Step 1: Calculate a loadings vector for the $X$ space, $\mathbf{p}_{a}$ called using the X-space scores: 
$$\mathbf{p}_{a}=(\mathbf{t}_{a}^{'}\mathbf{t}_{a})^{-1}\mathbf{X}_{a}^{'}\mathbf{t}_{a}$$
Step 2: Remove the predicted variability from $X$ and $Y$ Using the loadings, $\mathbf{p}_{a}$ just calculated
above, we remove from $\mathbf{X}_{a}$ the best prediction of $\mathbf{p}_{a}$, in other words, remove everything we can explain about it. We also remove any variance explained from $\mathbf{Y}_{a}$:
$$\mathbf{\hat{X}}_{a}=\mathbf{t}_{a}\mathbf{p}_{a}^{'}$$
$$\mathbf{\hat{Y}}_{a}=\mathbf{t}_{a}\mathbf{q}_{a}^{'}$$
$$\mathbf{X}_{a}=\mathbf{X}_{a}-\mathbf{\hat{X}}_{a}$$
$$\mathbf{Y}_{a}=\mathbf{Y}_{a}-\mathbf{\hat{Y}}_{a}$$

In [12]:
def pls(X, Y, no_components):
    MAXITER=10000
    CC=0.000000001
    Xc = (X-X.mean(axis=0))/X.std(axis=0,ddof=1)
    Yc = (Y-Y.mean(axis=0))/Y.std(axis=0,ddof=1)
    data_samples,X_variables = X.shape
    data_samples,Y_variables = Y.shape
    
    W = np.empty((X_variables, no_components))
    T = np.empty((data_samples, no_components))
    Q = np.empty((Y_variables, no_components))
    U = np.empty((data_samples, no_components))
    P = np.empty((X_variables, no_components))
    c = np.empty((no_components,))
    components = 0
    Xa = Xc
    Ya = Yc

    for j in range(0, no_components):
        ua = Ya[:,0]
        ITER = 0
        delU = CC * 10.0

        while ITER < MAXITER and delU > CC:                      
            wa = np.dot(Xa.T,ua)/np.dot(ua.T,ua)
            wa = wa/np.linalg.norm(wa, 2)
            ta = np.dot(Xa,wa)/np.dot(wa.T,wa)
            qa = np.dot(Ya.T,ta)/np.dot(ta.T,ta)
            qa = qa/np.linalg.norm(qa, 2)
            old_ua = ua
            ua = np.dot(Ya,qa)/np.dot(qa.T,qa)
            delU = np.linalg.norm(ua - old_ua)
            ITER += 1

        if ITER >= MAXITER:
            if ignore_failures:
                break
            else:
                raise ConvergenceError('PLS failed to converge for ' 'component: ' '{}'.format(components+1))
        W[:, j] = wa
        T[:, j] = ta
        Q[:, j] = qa
        U[:, j] = ua

        P[:, j] = np.dot(Xa.T,ta) / np.dot(ta.T,ta)
        Xa = Xa - np.outer(ta, P[:, j].T)
        Ya = Ya -  np.outer(ta, qa.T)
    return T,W,U,Q,P

In [13]:
[T,W,U,Q,P] = pls(X,Y,2)

In [14]:
Q

array([[ 0.81589566,  0.62819786],
       [ 0.57819917, -0.77805363]])

In [15]:
U

array([[-1.46171289,  0.41623171],
       [-0.48403379,  1.00515512],
       [ 0.49364531,  1.59407852],
       [-0.76886297, -0.64838508],
       [ 0.20881613, -0.05946167],
       [ 1.18649523,  0.52946173],
       [-0.07601305, -1.71300187],
       [ 0.90166605, -1.12407846]])

In [16]:
T

array([[-4.13421324,  0.3113111 ],
       [-1.5200581 ,  1.17675963],
       [ 1.09409705,  2.04220815],
       [-2.02355325, -0.90992154],
       [ 0.59060189, -0.04447301],
       [ 3.20475704,  0.82097551],
       [ 0.08710674, -2.13115418],
       [ 2.70126188, -1.26570566]])

In [17]:
W

array([[ 0.29004531, -0.4662135 ],
       [ 0.33287536, -0.36863102],
       [ 0.33287536, -0.36863102],
       [ 0.40629812,  0.03248028],
       [ 0.39020433,  0.2574492 ],
       [ 0.34728441,  0.42452259],
       [ 0.31368445,  0.50390541],
       [ 0.39739116, -0.09691315]])

In [18]:
U

array([[-1.46171289,  0.41623171],
       [-0.48403379,  1.00515512],
       [ 0.49364531,  1.59407852],
       [-0.76886297, -0.64838508],
       [ 0.20881613, -0.05946167],
       [ 1.18649523,  0.52946173],
       [-0.07601305, -1.71300187],
       [ 0.90166605, -1.12407846]])